/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IKittyPartyWinnerStrategy,
  IKittyPartyWinnerStrategyInterface,
} from "../IKittyPartyWinnerStrategy";

const _abi = [
  {
    inputs: [],
    name: "getLength",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "i",
        type: "uint256",
      },
    ],
    name: "getWinnerAtLocation",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getWinners",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_numberOfKittens",
        type: "uint256",
      },
    ],
    name: "initiateCheckWinner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IKittyPartyWinnerStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): IKittyPartyWinnerStrategyInterface {
    return new utils.Interface(_abi) as IKittyPartyWinnerStrategyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKittyPartyWinnerStrategy {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IKittyPartyWinnerStrategy;
  }
}
