/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IKittyPartyAccountant,
  IKittyPartyAccountantInterface,
} from "../IKittyPartyAccountant";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "kittyParty",
        type: "address",
      },
    ],
    name: "setupMinter",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IKittyPartyAccountant__factory {
  static readonly abi = _abi;
  static createInterface(): IKittyPartyAccountantInterface {
    return new utils.Interface(_abi) as IKittyPartyAccountantInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKittyPartyAccountant {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IKittyPartyAccountant;
  }
}
