/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IKittyPartyKeeper,
  IKittyPartyKeeperInterface,
} from "../IKittyPartyKeeper";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "kpController",
        type: "address",
      },
    ],
    name: "addKPController",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IKittyPartyKeeper__factory {
  static readonly abi = _abi;
  static createInterface(): IKittyPartyKeeperInterface {
    return new utils.Interface(_abi) as IKittyPartyKeeperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKittyPartyKeeper {
    return new Contract(address, _abi, signerOrProvider) as IKittyPartyKeeper;
  }
}
