/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  KittyPartyWinnerSelectionOptions,
  KittyPartyWinnerSelectionOptionsInterface,
} from "../KittyPartyWinnerSelectionOptions";

const _abi = [
  {
    inputs: [],
    name: "winnerStrategy",
    outputs: [
      {
        internalType: "enum KittyPartyWinnerSelectionOptions.WinningStrategy",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60806040526000805460ff1916600217905534801561001d57600080fd5b5060c38061002c6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80636f71462514602d575b600080fd5b60005460399060ff1681565b60405160449190604d565b60405180910390f35b60208101600583106087577f4e487b7100000000000000000000000000000000000000000000000000000000600052602160045260246000fd5b9190529056fea26469706673582212206065b4996e69aefe8875630abc3ed17e5a93bd73659b6cf8bf6a3c249153b23564736f6c634300080b0033";

export class KittyPartyWinnerSelectionOptions__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<KittyPartyWinnerSelectionOptions> {
    return super.deploy(
      overrides || {}
    ) as Promise<KittyPartyWinnerSelectionOptions>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): KittyPartyWinnerSelectionOptions {
    return super.attach(address) as KittyPartyWinnerSelectionOptions;
  }
  connect(signer: Signer): KittyPartyWinnerSelectionOptions__factory {
    return super.connect(signer) as KittyPartyWinnerSelectionOptions__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): KittyPartyWinnerSelectionOptionsInterface {
    return new utils.Interface(
      _abi
    ) as KittyPartyWinnerSelectionOptionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): KittyPartyWinnerSelectionOptions {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as KittyPartyWinnerSelectionOptions;
  }
}
