/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IKittyPartyYieldGeneratorInterface extends ethers.utils.Interface {
  functions: {
    "createLockedValue(bytes)": FunctionFragment;
    "lockedAmount(address)": FunctionFragment;
    "lockedPool(address)": FunctionFragment;
    "setPartyInfo(address,address)": FunctionFragment;
    "setPlatformDepositContractAddress(address)": FunctionFragment;
    "setPlatformRewardContractAddress(address,address)": FunctionFragment;
    "setPlatformWithdrawContractAddress(address)": FunctionFragment;
    "treasuryAddress()": FunctionFragment;
    "unwindLockedValue(bytes)": FunctionFragment;
    "yieldGenerated(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createLockedValue",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedAmount",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "lockedPool", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setPartyInfo",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformDepositContractAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformRewardContractAddress",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformWithdrawContractAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unwindLockedValue",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldGenerated",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createLockedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockedPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPartyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformDepositContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformRewardContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformWithdrawContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unwindLockedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yieldGenerated",
    data: BytesLike
  ): Result;

  events: {};
}

export class IKittyPartyYieldGenerator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IKittyPartyYieldGeneratorInterface;

  functions: {
    createLockedValue(
      arg0: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lockedAmount(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    lockedPool(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    setPartyInfo(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPlatformDepositContractAddress(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPlatformRewardContractAddress(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPlatformWithdrawContractAddress(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    treasuryAddress(overrides?: CallOverrides): Promise<[string]>;

    unwindLockedValue(
      arg0: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    yieldGenerated(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  createLockedValue(
    arg0: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lockedAmount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  lockedPool(arg0: string, overrides?: CallOverrides): Promise<string>;

  setPartyInfo(
    arg0: string,
    arg1: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPlatformDepositContractAddress(
    arg0: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPlatformRewardContractAddress(
    arg0: string,
    arg1: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPlatformWithdrawContractAddress(
    arg0: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  treasuryAddress(overrides?: CallOverrides): Promise<string>;

  unwindLockedValue(
    arg0: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  yieldGenerated(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    createLockedValue(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lockedAmount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    lockedPool(arg0: string, overrides?: CallOverrides): Promise<string>;

    setPartyInfo(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setPlatformDepositContractAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setPlatformRewardContractAddress(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setPlatformWithdrawContractAddress(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<void>;

    treasuryAddress(overrides?: CallOverrides): Promise<string>;

    unwindLockedValue(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    yieldGenerated(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    createLockedValue(
      arg0: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lockedAmount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    lockedPool(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    setPartyInfo(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPlatformDepositContractAddress(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPlatformRewardContractAddress(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPlatformWithdrawContractAddress(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    treasuryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    unwindLockedValue(
      arg0: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    yieldGenerated(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createLockedValue(
      arg0: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lockedAmount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lockedPool(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setPartyInfo(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPlatformDepositContractAddress(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPlatformRewardContractAddress(
      arg0: string,
      arg1: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPlatformWithdrawContractAddress(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    treasuryAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unwindLockedValue(
      arg0: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    yieldGenerated(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
