/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IKittyPartyWinnerStrategyInterface extends ethers.utils.Interface {
  functions: {
    "getLength()": FunctionFragment;
    "getWinnerAtLocation(uint256)": FunctionFragment;
    "getWinners()": FunctionFragment;
    "initiateCheckWinner(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getLength", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getWinnerAtLocation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initiateCheckWinner",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getLength", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWinnerAtLocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWinners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateCheckWinner",
    data: BytesLike
  ): Result;

  events: {};
}

export class IKittyPartyWinnerStrategy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IKittyPartyWinnerStrategyInterface;

  functions: {
    getLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    getWinnerAtLocation(
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getWinners(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    initiateCheckWinner(
      _numberOfKittens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getLength(overrides?: CallOverrides): Promise<BigNumber>;

  getWinnerAtLocation(
    i: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getWinners(overrides?: CallOverrides): Promise<BigNumber[]>;

  initiateCheckWinner(
    _numberOfKittens: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getLength(overrides?: CallOverrides): Promise<BigNumber>;

    getWinnerAtLocation(
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWinners(overrides?: CallOverrides): Promise<BigNumber[]>;

    initiateCheckWinner(
      _numberOfKittens: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getLength(overrides?: CallOverrides): Promise<BigNumber>;

    getWinnerAtLocation(
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWinners(overrides?: CallOverrides): Promise<BigNumber>;

    initiateCheckWinner(
      _numberOfKittens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getWinnerAtLocation(
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWinners(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initiateCheckWinner(
      _numberOfKittens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
